### PR TITLE
[SYSTEMDS][GIO] Generating Efficient Matrix and Frame Readers for Custom Data Formats by Example

### PR DESCRIPTION
**Pull request by fathollahzadeh**
This is an updated implementation of GIO, a system for generating efficient matrix and frame readers for custom data formats by example. Our GIO paper was published in SIGMOD 2023. The main improvements and extensions over the previous implementation are:

1. Support for both frame and matrix reader generation
2. Support for projection over the selected fields
3. Improved code generation that adapts to single/multi-threaded configuration
4. Support for single/multi-line record representations

Thanks for review.

### CODE REVIEW

**Comment by Baunsgaard** [comment]
Also, src/test/scripts/functions/iogen/data/Custom/F7/sample-aminer-author200.raw 
seems to be copied many times, are there differences in these files?

**Comment by fathollahzadeh** [comment]
> Hi @fathollahzadeh
> 
> Thanks for the isolated PR, i scrolled through it and it does not touch any files that would break existing code. I can take a closer look at another time, but given that it looks well tested i say if the automated tests pass then we merge it!
> 
> I have one question/request, if we can avoid adding one file : src/test/scripts/functions/iogen/data/XML/sample-autolead-xml200.raw
> 
> This is 21400 lines, can the test of xml parsing be reduced?
> 
> Best regards Sebastian

Hi @Baunsgaard 
Thank you for the prompt feedback and suggestions.
I have made the following changes:

1. Changed the dataset directory from "data" to "in", which should resolve the license error.
2. Removed duplicate datasets
3. Reduced the XML file sizes

Best,
Saeed

**Comment by fathollahzadeh** [comment]
> Also, src/test/scripts/functions/iogen/data/Custom/F7/sample-aminer-author200.raw seems to be copied many times, are there differences in these files?

resolved in the last commit.

**Comment by Baunsgaard** [comment]
It is just missing an exception on :
https://github.com/apache/systemds/blob/715b2fc523f700974ad1aa348d155553ed1bc52f/pom.xml#L636

for the path: src/test/scripts/functions/iogen/in/

**Comment by fathollahzadeh** [comment]
> It is just missing an exception on :
> 
> https://github.com/apache/systemds/blob/715b2fc523f700974ad1aa348d155553ed1bc52f/pom.xml#L636
> 
> for the path: src/test/scripts/functions/iogen/in/

can I add this line to pom.xml?
<exclude>src/test/scripts/functions/iogen/in/*/*/*</exclude> 
or, should I find another way?

**Comment by Baunsgaard** [comment]
> > It is just missing an exception on :
> > https://github.com/apache/systemds/blob/715b2fc523f700974ad1aa348d155553ed1bc52f/pom.xml#L636
> > 
> > for the path: src/test/scripts/functions/iogen/in/
> 
> can I add this line to pom.xml? `<exclude>src/test/scripts/functions/iogen/in/*/*/*</exclude> ` or, should I find another way?

yes, feel free to add it to the pom.xml. thanks.

**Comment by Baunsgaard** [comment]
Thanks for the contribution @fathollahzadeh ! I have merged it now.

**Pull request closed without merging**
