### PR TITLE
Create `CITATION.cff`

### PR DESCRIPTION
**Pull request by j143**
Preview: https://github.com/j143/systemds/tree/citation-cff (right panel, `cite this repository` dropdown!)

image

---

As per the following resources:
- https://graz.pure.elsevier.com/en/publications/systemds-a-declarative-machine-learning-system-for-the-end-to-end
- https://www.vldb.org/pvldb/vol9/p1425-boehm.pdf

Points:
1. Names from the SystemDS (2020), SystemML (2016) research papers
2. Names are not repeated, first appearance preserved

Questions 😃 
1. name-suffix for few names are they correct, unfortunately I am not familiar with some formats?
There are two options, `name-particle` and `name-suffix`

mail discussion at https://lists.apache.org/thread/zn7ngh8ymcv65o17t3wzz68189ll892b

### CODE REVIEW

**Comment by j143** [comment]
Hi @mboehm7!

Could you help me with further changes in this. Thanks a lot.

**Comment by mboehm7** [comment]
I'm a bit swamped in other work right now, but to come to it next week.

**Comment by j143** [comment]
Yeah. this can wait. thank for the note.

**Comment by phaniarnab** [comment]
This file currently provides a BibTex entry for the source code. Is there a way to add entries for the papers as well?

Examples:
Matthias Boehm, Iulian Antonov, Sebastian Baunsgaard, Mark Dokter, Robert Ginthör, Kevin Innerebner, Florijan Klezin, Stefanie N. Lindstaedt, Arnab Phani, Benjamin Rath, Berthold Reinwald, Shafaq Siddiqui, and Sebastian Benjamin
Wrede. 2020. SystemDS: A Declarative Machine Learning System for the End-toEnd Data Science Lifecycle. In CIDR

Matthias Boehm, Michael Dusenberry, Deron Eriksson, Alexandre V. Evfimievski, Faraz Makari Manshadi, Niketan Pansare, Berthold Reinwald, Frederick Reiss, Prithviraj Sen, Arvind Surve, and Shirish Tatikonda. 2016. SystemML: Declarative
Machine Learning on Spark. PVLDB 9, 13 (2016), 1425–1436

**Comment by j143** [comment]
> This file currently provides a BibTex entry for the source code. Is there a way to add entries for the papers as well?

Yes. We can add it as the reference literature for the software.

**Comment by corepointer** [comment]
Hi!
I had a look at the "cite this repository" drop down in your branch. Looks nice :) But the button "view citation file" does not do anything :shrug: 
What would also be nice: to link to the citation info from the Readme.md file.

Regards, Mark

**Comment by j143** [comment]
cc @mboehm7 - can you verify this once? 😃

**Comment by mboehm7** [comment]
Thanks for initiating this effort - generally this is a good idea. I would recommend two changes:
* For the software citation: use the 'Apache SystemDS Development Team' instead of the union of author names (as some of the mentioned names did not contribute a single commit), and the bibtex should include a URL to our github repo.
* Add the papers as separate inproceedings and article bibtex entries, similar to PyTorch: https://github.com/pytorch/pytorch/blob/master/CITATION

```
@inproceedings{BoehmADGIKLPR20,
  author    = {Matthias Boehm and
               Iulian Antonov and
               Sebastian Baunsgaard and
               Mark Dokter and
               Robert Ginth{\"{o}}r and
               Kevin Innerebner and
               Florijan Klezin and
               Stefanie N. Lindstaedt and
               Arnab Phani and
               Benjamin Rath and
               Berthold Reinwald and
               Shafaq Siddiqui and
               Sebastian Benjamin Wrede},
  title     = {{SystemDS: A Declarative Machine Learning System for the End-to-End
               Data Science Lifecycle}},
  booktitle = {{CIDR}},
  year      = {2020},
}

@article{BoehmDEEMPRRSST16,
  author    = {Matthias Boehm and
               Michael Dusenberry and
               Deron Eriksson and
               Alexandre V. Evfimievski and
               Faraz Makari Manshadi and
               Niketan Pansare and
               Berthold Reinwald and
               Frederick Reiss and
               Prithviraj Sen and
               Arvind Surve and
               Shirish Tatikonda},
  title     = {{SystemML: Declarative Machine Learning on Spark}},
  journal   = {{PVLDB}},
  volume    = {9},
  number    = {13},
  pages     = {1425--1436},
  year      = {2016},
  url       = {http://www.vldb.org/pvldb/vol9/p1425-boehm.pdf},
}
```

**Pull request merged**
