### PR TITLE
[SYSTEMDS-2926] AWS scripts update for EMR-7.0.0

### PR DESCRIPTION
**Pull request by lachezar-n**
The changes fix some general issues:
- creating and referencing the S3 buckets
- not assigning any sub-network for the cluster (bad practice + potential security vulnerability)

The changes also update the used EMR version to the currently most recent one: emr-7.0.0:
- configurations update
- exchanging Ganglia with AmazonCloudWatchAgent

While testing the script with the current repo version the following bug was observed: when launching SystemDS in execution mode "spark" an `IllegalCallerException` is thrown.
For running the command `spark-submit target/SystemDS.jar -f path/to/hello.dml -exec spark -stats -explain` the exact output in the console is:
```shell
...
--MAIN PROGRAM
----GENERIC (lines 1-1) [recompile=false]
------CP print Hello World.SCALAR.STRING.true _Var0.SCALAR.STRING 8
------CP rmvar _Var0


An Error Occurred : 
   IllegalCallerException -- java.lang.ref is not open to unnamed module @4eba373c

```

### CODE REVIEW

**Comment by j143** [comment]
Hi @lachezar-n , welcome to SystemDS project ✨

**Comment by j143** [comment]
LGTM. Thanks

**Comment by j143** [comment]
Hi @lachezar-n , about the error you are facing could you share more details

please make sure to use Java 11, Spark 3.x

**Comment by lachezar-n** [comment]
Hi @j143, thanks for the note about the execution, indeed I didn't know that Java 11 is required. 
EMR uses default Java version 8 so I made some changes to the the shell script to enforce using Java 11 on the Amazon cluster. I will post the changes as a new pull-request so the `run_systemds_script.sh` can execute successfully.

**Pull request merged**
