### PR TITLE
[SYSTEMDS-3086] Federated WDivMM - Federated Output

### PR DESCRIPTION
**Pull request by ywcb00**
Hi,
This PR adds the overwritten changes from the commit [5e3863842](https://github.com/apache/systemds/commit/5e386384296a781cf6d3adf1ffe52105e4356407) again.
It was overwritten by [6649bcd5b](https://github.com/apache/systemds/commit/6649bcd5bc8c32abae76aaf54315b48d79ff5397).

### CODE REVIEW

**Comment by sebwrede** [comment]
Do you know if it was overwritten on purpose?

**Comment by sebwrede** [comment]
We can merge this again, but I think that if the change could be overwritten without any tests failing then it is a hint that we should add some tests that actually needs this additional processing case. This could be done in another PR or in the current PR.

**Comment by ywcb00** [comment]
It wasn't overwritten on purpose.

The additional methods are already taken from the current test cases, but the tests do not verify that the output is kept federated.
We should definitely change the tests so that they fail if the output is not federated when it should be.
Since this is the case with several instructions, I will create a new jira task for this and add it with another PR.

Btw, do you know any better possibility to verify the federated output than performing an additional (unary) instruction on it (e.g., _fed_!=_) and verifying that this additional instruction is performed federated?

**Comment by sebwrede** [comment]
Creating a new Jira task sounds like a good idea. 
Computing an additional instruction and looking at the heavy-hitters is also the way I test federated outputs. You can see that in my current PR #1367.

**Comment by mboehm7** [comment]
LGTM - thanks for fixing this @ywcb00. The overwrite was my fault, it was unintentional and happened during a massive merge of ~40 commits with many conflicts.

**Pull request closed without merging**
