### PR TITLE
Notebook for SystemDS MLContext on databricks

### PR DESCRIPTION
**Pull request by j143**
**What this PR do?**
* Run SystemDS library loaded cluster, with MLContext.
* This notebook uses scala.

---
**TL;DR:**

image

### CODE REVIEW

**Comment by j143** [comment]
Protip: (setting up databricks cluster)
**Step 1:**

image

**Step 2.**

image

**Step 3.**

image

---
**Step 4.**

image

**Step 5.**

image

**Comment by Baunsgaard** [comment]
Completely unrelated note ! PR 1000 :+1:

**Comment by j143** [comment]
> Completely unrelated note ! PR 1000 👍

Thank you. I will take this as a LGTM.

**Comment by j143** [comment]
Hi, I am merging these changes as the working is apparent from the screenshot. Although, I do prefer at least one review from the community! :smile:

Feel free to challenge any commit. or give feedback at any point.

**Pull request closed without merging**
