### PR TITLE
N-Gram statistics using lineage

### PR DESCRIPTION
**Pull request by Jaybit0**
This PR is an extension to PR #2045 and implements support for data-dependent n-grams using and extending the existing lineage functionality. As we are dealing with DAGs which are not linear sequences of instructions, I implemented the extension in such a way that it tracks every instruction path of the length `n`. If we had for example the DAG `(a*b + c/d)` and wanted to record bigrams, the two operation sequences `[(*, +), (/, +)]` would be added to the bigram store. I also keep track of the individual data-types of each instruction which is why I extended the existing lineage functionality as the `_data` string is sometimes empty and contains inconsistent information.

The n-gram table now looks like this, where the arguments within brackets show the input parameters of an instruction (separated by `°`) and the suffix `[i]` represents the parameter index for the following instruction (e.g. for the first entry the result of `rblk` is used as the second paremeter for `ba+*`):
```
Most common 2-grams (sorted by absolute time):
  #  N-Gram                          Time(s)  StdDev(t)/Mean(t)  Count
  1  (rblk·MATRIX·FP64(MATRIX·FP64)    1,144         (, 1.067)      4
     [1], ba+*·MATRIX·FP64(MATRIX·F                                  
     P64 ° MATRIX·FP64))                                             
  2  (rblk·MATRIX·FP64(MATRIX·FP64)    0,853         (, 0.469)      3
     [0], ba+*·MATRIX·FP64(MATRIX·F                                  
     P64 ° MATRIX·FP64))                                             
  3  (createvar·MATRIX·FP64()[0], r    0,343    (0.627, 0.929)      2
     blk·MATRIX·FP64(MATRIX·FP64))                                   
  4  (rblk·MATRIX·FP64(MATRIX·FP64)    0,285                 -      1
     [0], cpvar·MATRIX·FP64(MATRIX·                                  
     FP64))                                                          
  5  (+*·MATRIX·FP64(MATRIX·FP64 °     0,153                 -      1
     SCALAR·FP64 ° MATRIX·FP64)[0],                                  
      write·MATRIX·FP64(MATRIX·FP64                                  
      ° L_SCALAR·STRING ° L_SCALAR·                                  
     STRING ° L_SCALAR·INT64))                                       
```
@mboehm7

### CODE REVIEW

**Comment by phaniarnab** [comment]
I am not fully aware of the goal of this project. But it seems to me that adding these new entries to the LineageItem class can significantly increase the size of each object, which in turn impacts the lineage tracing overhead, as well as the cache usage behavior. If materializing these entries for each object is absolutely necessary, I recommend writing a separate class (e.g., LineageItemExtended) connected via a single entry. However, as I am unsure about the full project, I will let @mboehm7 comment on this first.

**Comment by Jaybit0** [comment]
Yes this makes sense. As this functionality is hardly used in production, it is probably better to avoid this kind of overhead. I think I can work my way around this by storing the additional data in a hashmap linking the additional data to the object. Then it would add no overhead if the n-gram statistics option is switched off.

**Comment by Jaybit0** [comment]
I have now implemented the changes to not increase the object size of LineageItem. This will add some minor overhead to my code but execution speed should not matter too much when running those statistics.

**Comment by mboehm7** [comment]
@Jaybit0 could you please rebase this PR? It seems to include the commits from the previous (already merged) PR. Thanks.

**Comment by mboehm7** [comment]
LGTM - thanks for the patch @Jaybit0. During the merge I move the code from ProgramBlock into a dedicated method in statistics, and also removed all unnecessary imports.

**Pull request closed without merging**
