### PR TITLE
[SYSTEMDS-3172] Sparse MCSC Block

### PR DESCRIPTION
**Pull request by ReneEnjilian**
This pull request implements the Modified Compressed Sparse Column (MCSC) block. So far, most sparse blocks in SystemDS were row oriented (MCSR, CSR, DCSR). MCSC follows a similar design as MCSR but storing individual columns instead of rows. For simplicity, we reused the existing SparseRowVector/SparseRowScalar classes for the columns. The main contribution is in SparseBlockMCSC.java, where the entire structure is implemented. Further, testing has been added. 

Subsequent tasks may require a deeper integration into the system. Specifically, a deeper integration is required regarding alignment, iterators and merging with other matrices.

### CODE REVIEW

**Comment by Baunsgaard** [comment]
Hi @ReneEnjilian 

The tests does not show up in the code coverage because the new package of tests you added is not run in GitHub actions. 
to enable it simply add a new element in the list on:

https://github.com/apache/systemds/blob/de91f669b87589d390a4c2804658210bb54ce1d7/.github/workflows/javaTests.yml#L57

or add a new line with the elements if you know your tests take a long time (10 minutes +)

**Comment by mboehm7** [comment]
LGTM - thanks @ReneEnjilian. During the merge I reverted the unnecessary `MatrixBlock` changes, fixed the warnings, simplified the tests, and added the sparse component tests to the github actions. Furthermore, I also fixed the java doc issues, of the previous failures on main.

**Comment by ReneEnjilian** [comment]
> Hi @ReneEnjilian
> 
> The tests does not show up in the code coverage because the new package of tests you added is not run in GitHub actions. to enable it simply add a new element in the list on:
> 
> https://github.com/apache/systemds/blob/de91f669b87589d390a4c2804658210bb54ce1d7/.github/workflows/javaTests.yml#L57
> 
> or add a new line with the elements if you know your tests take a long time (10 minutes +)

Hi @Baunsgaard,
thanks for your response. I am sorry but I maybe dont really understand you. I did not add a new package (meaning directory) of tests. These were existing tests and I just adapted them mostly. Do you want me to add **.component.s**.** in javaTests.yml?

**Comment by Baunsgaard** [comment]
> > Hi @ReneEnjilian
> > The tests does not show up in the code coverage because the new package of tests you added is not run in GitHub actions. to enable it simply add a new element in the list on:
> > https://github.com/apache/systemds/blob/de91f669b87589d390a4c2804658210bb54ce1d7/.github/workflows/javaTests.yml#L57
> > 
> > or add a new line with the elements if you know your tests take a long time (10 minutes +)
> 
> Hi @Baunsgaard, thanks for your response. I am sorry but I maybe dont really understand you. I did not add a new package (meaning directory) of tests. These were existing tests and I just adapted them mostly. Do you want me to add **.component.s**.** in javaTests.yml?

no worries Matthias added it.
24a5724dce4d15c9d3d08f90dd76dc0d61b6b358

**Pull request closed without merging**
