### PR TITLE
Alg docs

### PR DESCRIPTION
**Pull request by Baunsgaard**
Algorithm Documentation.

I have removed all examples, but kept the descriptions, and very few examples.
This means that there is no examples that could be incorrectly showing how to run systemds.
in general we are moving towards supporting the algorithms as builtin, such that you don't need to call a specific algorithm from the outside, but is able to utilize them in scripts instead, without having to use the source keyword, that is somewhat error prone in nested situations.

### CODE REVIEW

**Comment by j143** [comment]
**Review summary:**

items to review:
1. Latex syntax
2. Content correctness
3. Content flow

---

- [ ] Descriptive statistics
- [ ] Classification
- [ ] Clustering
---
- [ ] Regression
- [ ] Matrix Factorization
---
- [ ] Survival Analysis
- [ ] Factorization machines

**Comment by j143** [comment]
Hi @Baunsgaard - I have made some minor changes and pushed to my [`master`](https://github.com/j143/systemds/tree/master) branch. (above comment)

Few things:
1. Let us decide about the content width for markdown edits laterally.
2. Consideration to tex rendering.

**Comment by Baunsgaard** [comment]
i tried to make it consistent at least in the text how wide it is,
the tables them selves and equations are harder to make a consistent width.

Do you intend me to merge what you have on your master?

**Comment by j143** [comment]
Hi @Baunsgaard

> Do you intend me to merge what you have on your master?

Yes, If possible can you take in my master branch and apply the commit appropriately.

**Comment by Baunsgaard** [comment]
Thanks for the review! and the edits!!
Both should now be on master. 
It was a slightly more difficult merge since i had to get your edits from your master branch.
The way i ended up doing it was to make it as two separated commits.
If there is any issues and i made any errors dont hesitate to point these out :+1: .

**Pull request closed without merging**
