### PR TITLE
[SYSTEMDS-3272] setSchema built-in to set the schema of frame from DML

### PR DESCRIPTION
**Pull request by Shafaq-Siddiqi**
- This built-in will allow changing the schema of a frame inside DML
  - Function call is placed inside  detectSchema test

### CODE REVIEW

**Comment by phaniarnab** [comment]
Thanks for this extension @Shafaq-Siddiqi.
This crashes because FP32 and INT32 are missing in the exact serialized size calculation logic (`FrameBlock.java::getExactSerializedSize()`).
I will investigate it further.

**Comment by Baunsgaard** [comment]
> Thanks for this extension @Shafaq-Siddiqi. This crashes because FP32 and INT32 are missing in the exact serialized size calculation logic (`FrameBlock.java::getExactSerializedSize()`). I will investigate it further.

This sounds related to the Bug just fixed in de3b9703d689d7877ccd8c7746ba10e42941fafa

**Comment by Baunsgaard** [comment]
Is this PR no longer relevant?

**Comment by phaniarnab** [comment]
Nope. It is a duplicate. Safe to close.

**Pull request closed without merging**
