### PR TITLE
[SYSTEMDS-3751, SYSTEMDS-3752, SYSTEMDS-3753] Python API missing buitin isNA, isNaN, isInf

### PR DESCRIPTION
**Pull request by e-strauss**
[SYSTEMDS-3751, SYSTEMDS-3752, SYSTEMDS-3753] Python API missing buitin isNA, isNaN, isInf

This patch adds the built in operator for isNA, isNaN, isInf to the python api.

### CODE REVIEW

**Comment by Baunsgaard** [comment]
is this operation only valid for matrices, if that is the case, we need to fix it in the system in general.
If not, we need to add it to the scalar node as well.

**Comment by e-strauss** [comment]
> is this operation only valid for matrices, if that is the case, we need to fix it in the system in general. If not, we need to add it to the scalar node as well.

I will check that, for now I used the dml-language-reference as guideline and checked in java only when operator is not mentioned.

**Comment by e-strauss** [comment]
updated for scalar as well

**Comment by Baunsgaard** [comment]
LGTM, merged, while merging i formatted the test, it is only minor things.
I can suggest that you adhere to the 'black' formatted code, since this is the auto formatter that I 'unofficially' use for the code in the Python API.

**Pull request closed without merging**
