### PR TITLE
[AMLS] [AMLS] Garch

### PR DESCRIPTION
**Pull request by JustYeti32**
Aim:
- build Garch(1,1) model

Planned Features:
- simulation of Garch(1,1) process
- fitting a Garch(1,1) to given data by max QMLE

### CODE REVIEW

**Comment by JustYeti32** [comment]
Hello everybody!

I would appreciate if somebody would check out L116 - L125 in builtin/garch.dml
There I encounter some unexpected behavior - maybe a bug? In any case I would appreciate a look. 

regards

**Comment by Baunsgaard** [comment]
When executing add a -debug flag (this enables java stack-trace output), and then post the entire program output you get here,
This will give us the precise location inside the system that the null pointer happens at.
That said, ideally the system should never get null pointer exceptions so you have most likely found a bug.

**Comment by JustYeti32** [comment]
mario@mario-MS-7C95:~/github/systemds/scripts/builtin$ systemds garch.dml -debug
###############################################################################
#  SYSTEMDS_ROOT= ../..
#  SYSTEMDS_JAR_FILE= ../../target/SystemDS.jar
#  CONFIG_FILE= 
#  LOG4JPROP= -Dlog4j.configuration=file:../../conf/log4j.properties
#  CLASSPATH= ../../target/SystemDS.jar:../../lib/*:../../target/lib/*
#  HADOOP_HOME= /home/mario/github/systemds/target/hadoop-test/org/apache/hadoop
#
#  Running script garch.dml locally with opts: -debug
###############################################################################
Executing command:     java       -Xmx4g      -Xms4g      -Xmn400m    -cp ../../target/SystemDS.jar:../../lib/*:../../target/lib/*   -Dlog4j.configuration=file:../../conf/log4j.properties   org.apache.sysds.api.DMLScript   -f garch.dml   -exec singlenode      -debug


An Error Occured : 
           ParseException -- An Parsing exception occured
     NullPointerException -- null

org.apache.sysds.parser.ParseException: An Parsing exception occured
        at org.apache.sysds.parser.DMLTranslator.processExpression(DMLTranslator.java:1611)
        at org.apache.sysds.parser.DMLTranslator.constructHops(DMLTranslator.java:1139)
        at org.apache.sysds.parser.DMLTranslator.constructHopsForFunctionControlBlock(DMLTranslator.java:1374)
        at org.apache.sysds.parser.DMLTranslator.constructHops(DMLTranslator.java:965)
        at org.apache.sysds.parser.DMLTranslator.constructHops(DMLTranslator.java:263)
        at org.apache.sysds.parser.DMLTranslator.constructHops(DMLTranslator.java:254)
        at org.apache.sysds.api.DMLScript.execute(DMLScript.java:391)
        at org.apache.sysds.api.DMLScript.executeScript(DMLScript.java:266)
        at org.apache.sysds.api.DMLScript.main(DMLScript.java:164)
Caused by: java.lang.NullPointerException
        at org.apache.sysds.hops.BinaryOp.<init>(BinaryOp.java:101)
        at org.apache.sysds.parser.DMLTranslator.processBinaryExpression(DMLTranslator.java:1756)
        at org.apache.sysds.parser.DMLTranslator.processExpression(DMLTranslator.java:1542)
        ... 8 more

**Comment by Baunsgaard** [comment]
the bug seems to be related to calling a function twice with the same arguments, this makes our compiler return null in one of the calls. so there definally is a bug in our system.

if you need to call it twice with the same arguments i suggest making a temporary variable like so:

```R
r =  qmle(Xt, nb_a0, arch_coef, var_coef)
df_a0 = r - curr_qmle
df_a0 = r - curr_qmle
```
but thanks for spotting a bug, i will ad a JIRA task to fix it.

**Comment by Baunsgaard** [comment]
also while i am looking, i would suggest adding a test inside src/test/java/org/apache/sysds/test/functions/builtin that automate the testing of this new builtin.

**Comment by JustYeti32** [comment]
Thank you for having a look and your suggestions!
I will definately incorporate some tests and make sure everything works as expected.

**Comment by mboehm7** [comment]
Thanks for catching this issue @JustYeti32 - this is now fixed in main and it was a rather complex case where hoisting multiple functions out of expressions affected each other. With the change the test script runs through just fine, we now added the respective tests and much better error handling.

**Comment by j143** [comment]
Hi @JustYeti32, your script is working now.

```sh
spark-submit ./target/SystemDS.jar -f ./garch.dml -debug
```


<details>
  <summary>Output</summary>

```log

500
0.1465992000635401
inside fct
0.4953763721731841
0.16662955948948133
0.5139428358834109
arch_coef
0.16662955948948133
2021-05-14 09:07:51 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:51 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:51 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5486355770452269
0.143963405024472
0.5671089367003042
arch_coef
0.143963405024472
2021-05-14 09:07:51 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:51 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5575099506987744
0.18387546158151635
0.5002680823800243
arch_coef
0.18387546158151635
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5617856260447684
0.18168832532508336
0.5224789046199482
arch_coef
0.18168832532508336
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5340070916896925
0.1515061489091135
0.5718176153552492
arch_coef
0.1515061489091135
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5675331949522027
0.17258134095835503
0.5024475266312846
arch_coef
0.17258134095835503
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5594974002032855
0.1524429867325436
0.5575131871765586
arch_coef
0.1524429867325436
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5408704415549264
0.16589084968418205
0.5258133459717219
arch_coef
0.16589084968418205
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.

inside fct
0.5209856201311941
0.15171010554582864
0.5233097391731367
arch_coef
0.15171010554582864
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_a0 has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_arch_coef has wrong value type: INT64.
2021-05-14 09:07:52 WARN  ProgramBlock:159 - Function output diff_var_coef has wrong value type: INT64.
```
</details>

---

If adding tests is overwhelming for you, just complete this script with correct numeric output.
We will help you with the tests! 😃

**Comment by JustYeti32** [comment]
Great to hear it could be fixed! @j143 thank you for offering your help, I will happily come back to it if need be!

**Comment by JustYeti32** [comment]
@j143 most literature suggests the [BHHH algorithm](https://en.wikipedia.org/wiki/Berndt%E2%80%93Hall%E2%80%93Hall%E2%80%93Hausman_algorithm) or [BFGS](https://en.wikipedia.org/wiki/Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm) (like it is used in R). I think the best move would be to update to such a proper optimizer if it becomes available for systemds. 

For this optimization method I followed the advice of @mboehm7 who suggested using a sort of meta-heuristic in order to avoid the complexity of implementing one of the above. I however tried to incorporate some ideas of gradient descent and ideas of simulated annealing.

**Comment by JustYeti32** [comment]
@mboehm7

**Comment by mboehm7** [comment]
LGTM - thanks for the patch @JustYeti32. In general this is an awesome initial version. I'll merge it in hopefully tomorrow with a few minor tweaks and additional TODOs for future vectorization.

**Pull request closed without merging**
