### PR TITLE
[SYSTEMDS-3736] Python API Builtin sqrt 

### PR DESCRIPTION
**Pull request by e-strauss**
This patch adds the built in operator for square root to the python api.

I will start adding test cases for the auto generated builtins and other built in operators in separate PRs.

### CODE REVIEW

**Comment by Baunsgaard** [comment]
Hi @e-strauss 

Could you make a separate PR with just the auto generated files. 
If we merge this first it will clean up the individual other PRs.

Furthermore, i have added an epic task in JIRA: https://issues.apache.org/jira/browse/SYSTEMDS-3732

Use it to add more builtin's missing.

Thanks

**Comment by e-strauss** [comment]
@Baunsgaard sure, done.

**Comment by e-strauss** [comment]
@Baunsgaard sure, np

**Comment by Baunsgaard** [comment]
LGTM and Merged

**Pull request closed without merging**
