### PR TITLE
[DIA] TomekLink

### PR DESCRIPTION
**Pull request by JustYeti32**

### CODE REVIEW

**Comment by JustYeti32** [comment]
Everything apart from the missing "unbalanced" R-package should work.

**Review by corepointer — APPROVED** [review]
LGTM - Thanks four your pull request. Test seems to run fine locally. I'll merge it with some minor modifications concerning the missing R package as soon as we've installed that to our CI environment.

**Comment by corepointer** [comment]
Thanks again for your commit! I merged it as issue SYSTEMDS-2877 with minor formatting modifications (indentation).

**Comment by JustYeti32** [comment]
Thanks for the review and the adjustments!

**Pull request closed without merging**
