### PR TITLE
[DOC] Documentation for builtin OutlierBySd function

### PR DESCRIPTION
**Pull request by wizard-420**
This PR contains documentation for outlierBySd Function

### CODE REVIEW

**Comment by j143** [comment]
Hi @wizard-420 - Let us make sure that this PR contains the changes related to `OutlierBySd` only. 😸

**Comment by wizard-420** [comment]
> Hi @wizard-420 - Let us make sure that this PR contains the changes related to `OutlierBySd` only. smile_cat

sorry I got confused

**Comment by j143** [comment]
Hi @wizard-420  - you are working on this!

**Comment by j143** [comment]
Closing this due to inactivity. Please reopen if needed. Thanks for contributing.

If you would like to contribute to the project 
1. Browse https://issues.apache.org/jira/projects/SYSTEMML/issues
2. or start a discussion on mailing list at dev@systemds.apache.org

**Pull request closed without merging**
